"""Added 'collected_questions' table

Revision ID: 8420d398566b
Revises: 
Create Date: 2023-06-04 13:32:33.067296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8420d398566b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=900), nullable=False),
    sa.Column('answer_text', sa.String(length=300), nullable=False),
    sa.Column('original_creation_time', sa.String(length=50), nullable=False),
    sa.Column('time_added_to_db', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collected_questions')),
    sa.UniqueConstraint('id', name=op.f('uq_collected_questions_id')),
    sa.UniqueConstraint('question_id', name=op.f('uq_collected_questions_question_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collected_questions')
    # ### end Alembic commands ###
