"""collected_questions_table

Revision ID: 99ad6a918e64
Revises: ebe6f42f70eb
Create Date: 2023-05-29 17:34:48.397350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ad6a918e64'
down_revision = 'ebe6f42f70eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=900), nullable=False),
    sa.Column('answer_text', sa.String(length=300), nullable=False),
    sa.Column('original_creation_time', sa.String(length=50), nullable=False),
    sa.Column('time_added_to_db', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collected_questions')),
    sa.UniqueConstraint('id', name=op.f('uq_collected_questions_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collected_questions')
    # ### end Alembic commands ###
