version: '3'

services:
  app:
    build:
      context: .
      dockerfile: first_task.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - some-name
    volumes:
      - .:/opt/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - bewisetask1_db_1

  bewisetask1_db_1:
    container_name: bewisetask1_db_1
    image: postgres:15.3-bullseye
    ports:
      - "5433:5432"
    networks:
      - some-name
    environment:
      - POSTGRES_DB=test_bs1
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=qwerty1234
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

networks:
  some-name:
    driver: bridge